<?php
    define("DRIVER","pgsql");
    define("DBHOST","localhost");
    define("DBPORT","5432");
    define("DBNAME","agenda");
    define("DBCHARSET","utf8mb4");
    define("DBUSER","postgres");
    define("DBPASSWORD","154326");
?>