<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen;

use Diogodg\Neoorm\Query\Expr\ColumnRef;
use Diogodg\Neoorm\Query\Table;
use Diogodg\Neoorm\Schema\Type\TypeName;
use Diogodg\Neoorm\Schema\Type\TypeSpec;
use Tests\Golden\Codegen\Rows\ScheduleUserRow;

/**
 * Referência tipada a `schedule_user`.
 *
 * @extends Table<ScheduleUserRow>
 */
final class ScheduleUserTable extends Table
{
    public const string NAME = 'schedule_user';

    /** @var ColumnRef<int> */
    public readonly ColumnRef $schedule_id;

    /** @var ColumnRef<int> */
    public readonly ColumnRef $user_id;

    public function __construct(?string $alias = null)
    {
        parent::__construct($alias);

        $qualifier = $alias ?? self::NAME;

        $this->schedule_id = new ColumnRef(
            $qualifier,
            'schedule_id',
            new TypeSpec(TypeName::Int),
            true,
        );
        $this->user_id = new ColumnRef(
            $qualifier,
            'user_id',
            new TypeSpec(TypeName::Int),
            true,
        );
    }

    public function tableName(): string
    {
        return self::NAME;
    }

    /**
     * @return class-string<ScheduleUserRow>
     */
    public function rowClass(): string
    {
        return ScheduleUserRow::class;
    }

    /**
     * @param array<string,mixed> $row
     */
    public function hydrate(array $row): ScheduleUserRow
    {
        return ScheduleUserRow::fromRow($row);
    }

    /**
     * @return array<string,ColumnRef<mixed>>
     */
    public function columnRefs(): array
    {
        return [
            'schedule_id' => $this->schedule_id,
            'user_id' => $this->user_id,
        ];
    }

    /**
     * @return list<string>
     */
    public function primaryKeyColumns(): array
    {
        return ['schedule_id', 'user_id'];
    }

    public function autoIncrementColumn(): ?string
    {
        return null;
    }

    /**
     * @return list<string>
     */
    public function requiredInsertColumns(): array
    {
        return ['schedule_id', 'user_id'];
    }

    public function as(string $alias): static
    {
        return new self($alias);
    }
}
