<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen;

use Diogodg\Neoorm\Query\Table;
use InvalidArgumentException;

/**
 * As tabelas do schema, tipadas.
 *
 * ```php
 * use Tests\Golden\Codegen\Tables;
 *
 * $u = Tables::users();
 * $db->select()->from($u)->where(eq($u->email, $email))->all();
 * ```
 */
final class Tables
{
    /**
     * Nome de tabela => classe de referência. Usado por `Model::ref()`.
     *
     * @var array<string,class-string<Table<object>>>
     */
    public const MAP = [
        'schedule_user' => ScheduleUserTable::class,
        'users' => UsersTable::class,
    ];

    private function __construct()
    {
    }

    /**
     * A referência de uma tabela pelo NOME dela.
     *
     * É o caminho de `Model::ref()`, que sabe o nome da tabela (a constante do model)
     * e não a classe gerada. Quem escreve consulta à mão prefere o método nomeado
     * abaixo: ele devolve o tipo concreto sem depender de anotação nenhuma.
     *
     * @return Table<object>
     */
    public static function for(string $table, ?string $alias = null): Table
    {
        $class = self::MAP[strtolower($table)] ?? null;

        if ($class === null) {
            throw new InvalidArgumentException(
                "Nenhuma tabela gerada chamada '{$table}'. "
                . 'Se o model é novo, rode: vendor/bin/neoorm generate:types',
            );
        }

        return new $class($alias);
    }

    public static function scheduleUser(?string $alias = null): ScheduleUserTable
    {
        return new ScheduleUserTable($alias);
    }

    public static function users(?string $alias = null): UsersTable
    {
        return new UsersTable($alias);
    }
}
