<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen;

use DateTimeImmutable;
use Diogodg\Neoorm\Query\Expr\ColumnRef;
use Diogodg\Neoorm\Query\Table;
use Diogodg\Neoorm\Schema\Type\TypeName;
use Diogodg\Neoorm\Schema\Type\TypeSpec;
use Tests\Golden\Codegen\Enums\UsersStatus;
use Tests\Golden\Codegen\Rows\UsersRow;

/**
 * Referência tipada a `users`.
 *
 * @extends Table<UsersRow>
 */
final class UsersTable extends Table
{
    public const string NAME = 'users';

    /** @var ColumnRef<string> */
    public readonly ColumnRef $name;

    /** @var ColumnRef<int> */
    public readonly ColumnRef $id;

    /** @var ColumnRef<string|null> */
    public readonly ColumnRef $phone;

    /** @var ColumnRef<numeric-string> */
    public readonly ColumnRef $balance;

    /** @var ColumnRef<bool> */
    public readonly ColumnRef $active;

    /** @var ColumnRef<DateTimeImmutable> */
    public readonly ColumnRef $created_at;

    /** @var ColumnRef<UsersStatus> */
    public readonly ColumnRef $status;

    /** @var ColumnRef<string|null> */
    public readonly ColumnRef $nickname;

    /** @var ColumnRef<mixed> */
    public readonly ColumnRef $metadata;

    /** @var ColumnRef<string|null> */
    public readonly ColumnRef $avatar;

    /** @var ColumnRef<string|null> */
    public readonly ColumnRef $code;

    public function __construct(?string $alias = null)
    {
        parent::__construct($alias);

        $qualifier = $alias ?? self::NAME;

        $this->name = new ColumnRef(
            $qualifier,
            'name',
            new TypeSpec(TypeName::Varchar, length: 120),
            true,
        );
        $this->id = new ColumnRef(
            $qualifier,
            'id',
            new TypeSpec(TypeName::Int),
            true,
        );
        $this->phone = new ColumnRef(
            $qualifier,
            'phone',
            new TypeSpec(TypeName::Varchar, length: 20),
            false,
        );
        $this->balance = new ColumnRef(
            $qualifier,
            'balance',
            new TypeSpec(TypeName::Decimal, precision: 10, scale: 2),
            true,
        );
        $this->active = new ColumnRef(
            $qualifier,
            'active',
            new TypeSpec(TypeName::Boolean),
            true,
        );
        $this->created_at = new ColumnRef(
            $qualifier,
            'created_at',
            new TypeSpec(TypeName::DateTime),
            true,
        );
        $this->status = new ColumnRef(
            $qualifier,
            'status',
            new TypeSpec(TypeName::Enum, values: ['ativo', 'bloqueado', 'pendente']),
            true,
        );
        $this->nickname = new ColumnRef(
            $qualifier,
            'nickname',
            new TypeSpec(TypeName::Varchar, length: 40),
            false,
        );
        $this->metadata = new ColumnRef(
            $qualifier,
            'metadata',
            new TypeSpec(TypeName::Json),
            false,
        );
        $this->avatar = new ColumnRef(
            $qualifier,
            'avatar',
            new TypeSpec(TypeName::Blob),
            false,
        );
        $this->code = new ColumnRef(
            $qualifier,
            'code',
            new TypeSpec(TypeName::Char, length: 10),
            false,
        );
    }

    public function tableName(): string
    {
        return self::NAME;
    }

    /**
     * @return class-string<UsersRow>
     */
    public function rowClass(): string
    {
        return UsersRow::class;
    }

    /**
     * @param array<string,mixed> $row
     */
    public function hydrate(array $row): UsersRow
    {
        return UsersRow::fromRow($row);
    }

    /**
     * @return array<string,ColumnRef<mixed>>
     */
    public function columnRefs(): array
    {
        return [
            'name' => $this->name,
            'id' => $this->id,
            'phone' => $this->phone,
            'balance' => $this->balance,
            'active' => $this->active,
            'created_at' => $this->created_at,
            'status' => $this->status,
            'nickname' => $this->nickname,
            'metadata' => $this->metadata,
            'avatar' => $this->avatar,
            'code' => $this->code,
        ];
    }

    /**
     * @return list<string>
     */
    public function primaryKeyColumns(): array
    {
        return ['id'];
    }

    public function autoIncrementColumn(): string
    {
        return 'id';
    }

    /**
     * @return list<string>
     */
    public function requiredInsertColumns(): array
    {
        return ['name'];
    }

    public function as(string $alias): static
    {
        return new self($alias);
    }
}
