<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen\Rows;

use DateTimeImmutable;
use Diogodg\Neoorm\Runtime\Casting\Cast;
use Tests\Golden\Codegen\Enums\UsersStatus;

/**
 * Uma linha de `users`.
 *
 * Usuários do sistema
 */
final readonly class UsersRow
{
    /**
     * @param string $name Nome do usuário
     * @param string|null $phone
     * @param numeric-string $balance
     * @param string|null $nickname
     * @param string|null $avatar
     * @param string|null $code
     */
    public function __construct(
        public string $name,
        public int $id,
        public ?string $phone,
        public string $balance,
        public bool $active,
        public DateTimeImmutable $created_at,
        public UsersStatus $status,
        public ?string $nickname,
        public mixed $metadata,
        public ?string $avatar,
        public ?string $code,
    ) {
    }

    /**
     * Hidrata a partir de uma linha crua do PDO.
     *
     * Chave ausente vira null e o caster recusa quando a coluna é NOT NULL: uma linha
     * meio montada em silêncio é pior que a exceção que diz qual SELECT não trouxe o quê.
     *
     * @param array<string,mixed> $row
     */
    public static function fromRow(array $row): self
    {
        return new self(
            name: Cast::string($row['name'] ?? null, 'users.name'),
            id: Cast::int($row['id'] ?? null, 'users.id'),
            phone: Cast::nullableString($row['phone'] ?? null, 'users.phone'),
            balance: Cast::decimal($row['balance'] ?? null, 'users.balance'),
            active: Cast::bool($row['active'] ?? null, 'users.active'),
            created_at: Cast::dateTime($row['created_at'] ?? null, 'users.created_at'),
            status: UsersStatus::from(Cast::string($row['status'] ?? null, 'users.status')),
            nickname: Cast::nullableString($row['nickname'] ?? null, 'users.nickname'),
            metadata: Cast::nullableJson($row['metadata'] ?? null, 'users.metadata'),
            avatar: Cast::nullableString($row['avatar'] ?? null, 'users.avatar'),
            code: Cast::nullableChar($row['code'] ?? null, 'users.code'),
        );
    }

    /**
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'id' => $this->id,
            'phone' => $this->phone,
            'balance' => $this->balance,
            'active' => $this->active,
            'created_at' => $this->created_at,
            'status' => $this->status,
            'nickname' => $this->nickname,
            'metadata' => $this->metadata,
            'avatar' => $this->avatar,
            'code' => $this->code,
        ];
    }
}
