-- Superfície do dialeto pgsql, gerada por DialectGoldenTest.
-- Regenere com: composer test:snapshots

-- [create_table] cria a tabela 'product' com 7 colunas
CREATE TABLE "product" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" VARCHAR(120) NOT NULL,
	"price" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"active" BOOLEAN NOT NULL DEFAULT true,
	"description" TEXT,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"category" INTEGER,
	CONSTRAINT "product_pk" PRIMARY KEY ("id")
);
--> statement-breakpoint
COMMENT ON TABLE "product" IS 'Catálogo de produtos';
--> statement-breakpoint
COMMENT ON COLUMN "product"."name" IS 'Nome do produto';

-- [drop_table] remove a tabela 'product'
DROP TABLE "product";

-- [rename_table] renomeia a tabela 'product' para 'item'
ALTER TABLE "product" RENAME TO "item";

-- [set_table_comment] define o comentário da tabela 'product'
COMMENT ON TABLE "product" IS 'Catálogo revisado';

-- [set_table_options] define engine InnoDB e collation utf8mb4_0900_ai_ci na tabela 'product'
-- (nenhum statement neste dialeto)

-- [add_column] adiciona a coluna 'product.sku' (VARCHAR(32))
ALTER TABLE "product" ADD COLUMN "sku" VARCHAR(32) NOT NULL;
--> statement-breakpoint
COMMENT ON COLUMN "product"."sku" IS 'Código do produto';

-- [drop_column] remove a coluna 'product.description'
ALTER TABLE "product" DROP COLUMN "description";

-- [rename_column] renomeia a coluna 'product.name' para 'title'
ALTER TABLE "product" RENAME COLUMN "name" TO "title";

-- [alter_column] altera a coluna 'product.name' (tipo, comentário)
ALTER TABLE "product" ALTER COLUMN "name" TYPE VARCHAR(200) USING "name"::VARCHAR(200);
--> statement-breakpoint
COMMENT ON COLUMN "product"."name" IS 'Nome comercial';

-- [add_primary_key] define a chave primária de 'product' em (id)
ALTER TABLE "product" ADD CONSTRAINT "product_pk" PRIMARY KEY ("id");

-- [drop_primary_key] remove a chave primária de 'product'
ALTER TABLE "product" DROP CONSTRAINT "product_pk";

-- [add_unique_constraint] adiciona a restrição de unicidade 'product_sku_unique' em 'product' (sku)
ALTER TABLE "product" ADD CONSTRAINT "product_sku_unique" UNIQUE ("sku");

-- [drop_unique_constraint] remove a restrição de unicidade 'product_sku_unique' de 'product'
ALTER TABLE "product" DROP CONSTRAINT "product_sku_unique";

-- [create_index] cria o índice 'product_category_index' em 'product' (category)
CREATE INDEX "product_category_index" ON "product" ("category");

-- [drop_index] remove o índice 'product_category_index' de 'product'
DROP INDEX "product_category_index";

-- [add_foreign_key] adiciona a foreign key 'product_category_category_id_fk' em 'product' (category) -> category (id)
ALTER TABLE "product" ADD CONSTRAINT "product_category_category_id_fk" FOREIGN KEY ("category") REFERENCES "category" ("id");

-- [drop_foreign_key] remove a foreign key 'product_category_category_id_fk' de 'product'
ALTER TABLE "product" DROP CONSTRAINT "product_category_category_id_fk";

-- [add_check_constraint] adiciona a restrição CHECK 'product_b3940f6d_check' em 'product'
ALTER TABLE "product" ADD CONSTRAINT "product_b3940f6d_check" CHECK (price >= 0);

-- [drop_check_constraint] remove a restrição CHECK 'product_b3940f6d_check' de 'product'
ALTER TABLE "product" DROP CONSTRAINT "product_b3940f6d_check";

-- [raw_sql] executa SQL cru: CREATE VIEW active_product AS SELECT id FROM product WHER...
CREATE VIEW active_product AS SELECT id FROM product WHERE active = 1;

-- [create_table_composite_pk] cria a tabela 'product_category' com 2 colunas
CREATE TABLE "product_category" (
	"product" INTEGER NOT NULL,
	"category" INTEGER NOT NULL,
	CONSTRAINT "product_category_pk" PRIMARY KEY ("product", "category")
);

-- [create_table_without_primary_key] cria a tabela 'import_log' com 2 colunas
CREATE TABLE "import_log" (
	"payload" TEXT,
	"at" TIMESTAMP
);

-- [create_table_reserved_words] cria a tabela 'order' com 4 colunas
CREATE TABLE "order" (
	"select" INTEGER NOT NULL,
	"from" VARCHAR(40),
	"default" BOOLEAN NOT NULL DEFAULT false,
	"user" VARCHAR(40),
	CONSTRAINT "order_pk" PRIMARY KEY ("select")
);

-- [create_table_hostile_comment] cria a tabela 'audit_log' com 2 colunas
CREATE TABLE "audit_log" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"detail" TEXT,
	CONSTRAINT "audit_log_pk" PRIMARY KEY ("id")
);
--> statement-breakpoint
COMMENT ON COLUMN "audit_log"."detail" IS 'aspa '' dupla " barra \ nova
linha acentuação 🎯';

-- [set_table_comment_removed] remove o comentário da tabela 'product'
COMMENT ON TABLE "product" IS NULL;

-- [set_table_options_empty] restaura as opções padrão da tabela 'product'
-- (nenhum statement neste dialeto)

-- [add_column_default_empty_string] adiciona a coluna 'product.note' (VARCHAR(80))
ALTER TABLE "product" ADD COLUMN "note" VARCHAR(80) NOT NULL DEFAULT '';

-- [add_column_expression_default] adiciona a coluna 'product.updated_at' (TIMESTAMP)
ALTER TABLE "product" ADD COLUMN "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- [alter_column_type_and_default] altera a coluna 'product.code' (tipo)
ALTER TABLE "product" ALTER COLUMN "code" DROP DEFAULT;
--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "code" TYPE INTEGER USING "code"::INTEGER;
--> statement-breakpoint
ALTER TABLE "product" ALTER COLUMN "code" SET DEFAULT 0;

-- [alter_column_comment_only] altera a coluna 'product.name' (comentário)
COMMENT ON COLUMN "product"."name" IS 'depois';

-- [alter_column_drop_not_null] altera a coluna 'product.description' (nulidade)
ALTER TABLE "product" ALTER COLUMN "description" DROP NOT NULL;

-- [alter_column_drop_default] altera a coluna 'product.price' (default)
ALTER TABLE "product" ALTER COLUMN "price" DROP DEFAULT;

-- [alter_column_add_identity] altera a coluna 'product.id' (auto incremento)
ALTER TABLE "product" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- [alter_column_drop_identity] altera a coluna 'product.id' (auto incremento)
ALTER TABLE "product" ALTER COLUMN "id" DROP IDENTITY;

-- [drop_primary_key_with_auto_increment] remove a chave primária de 'product'
ALTER TABLE "product" DROP CONSTRAINT "product_pk";

-- [create_index_unique] cria o índice único 'product_sku_unique_index' em 'product' (sku)
CREATE UNIQUE INDEX "product_sku_unique_index" ON "product" ("sku");

-- [create_index_multi_column] cria o índice 'product_category_name_index' em 'product' (category, name)
CREATE INDEX "product_category_name_index" ON "product" ("category", "name");

-- [add_foreign_key_cascade] adiciona a foreign key 'product_category_category_id_fk' em 'product' (category) -> category (id)
ALTER TABLE "product" ADD CONSTRAINT "product_category_category_id_fk" FOREIGN KEY ("category") REFERENCES "category" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- [add_foreign_key_set_null] adiciona a foreign key 'product_category_category_id_fk' em 'product' (category) -> category (id)
ALTER TABLE "product" ADD CONSTRAINT "product_category_category_id_fk" FOREIGN KEY ("category") REFERENCES "category" ("id") ON DELETE SET NULL;

-- [add_foreign_key_composite] adiciona a foreign key 'product_category_product_category_catalog_entry_produc_d3dc2462' em 'product_category' (product, category) -> catalog_entry (product, category)
ALTER TABLE "product_category" ADD CONSTRAINT "product_category_product_category_catalog_entry_produc_d3dc2462" FOREIGN KEY ("product", "category") REFERENCES "catalog_entry" ("product", "category") ON DELETE CASCADE;

-- [add_foreign_key_self_reference] adiciona a foreign key 'category_parent_category_id_fk' em 'category' (parent) -> category (id)
ALTER TABLE "category" ADD CONSTRAINT "category_parent_category_id_fk" FOREIGN KEY ("parent") REFERENCES "category" ("id") ON DELETE SET NULL;

-- [migrations_table] tabela de controle do runner
CREATE TABLE IF NOT EXISTS "_neoorm_migrations" (
	"tag" VARCHAR(191) NOT NULL,
	"hash" CHAR(64) NOT NULL,
	"statements" INTEGER NOT NULL DEFAULT 0,
	"applied_index" INTEGER NOT NULL DEFAULT 0,
	"status" VARCHAR(16) NOT NULL DEFAULT 'running',
	"error" TEXT,
	"started_at" TIMESTAMP,
	"finished_at" TIMESTAMP,
	CONSTRAINT "_neoorm_migrations_pk" PRIMARY KEY ("tag")
);
