<?php

declare(strict_types=1);

namespace Diogodg\Neoorm\Codegen;

/**
 * Um arquivo gerado, como valor.
 *
 * O gerador devolve isto e **não escreve nada**. Só `FileSystemWriter` toca disco, e é o
 * que permite testar a geração inteira comparando strings — sem diretório temporário,
 * sem limpeza, sem teste que deixa lixo quando falha no meio.
 */
final readonly class GeneratedFile
{
    /**
     * Marcador reconhecido pelo GitHub para colapsar o diff. Também é o que autoriza o
     * writer a apagar o arquivo: sem ele, o writer assume que foi escrito à mão.
     */
    public const string MARKER = '@generated by neoorm';

    public function __construct(public string $relativePath, public string $contents)
    {
    }
}
