<?php

declare(strict_types=1);

namespace Diogodg\Neoorm\Dialect;

use Diogodg\Neoorm\Migrations\Exception\MigrationException;
use Diogodg\Neoorm\Migrations\Operation\AddCheckConstraint;
use Diogodg\Neoorm\Migrations\Operation\AddColumn;
use Diogodg\Neoorm\Migrations\Operation\AddForeignKey;
use Diogodg\Neoorm\Migrations\Operation\AddPrimaryKey;
use Diogodg\Neoorm\Migrations\Operation\AddUniqueConstraint;
use Diogodg\Neoorm\Migrations\Operation\AlterColumn;
use Diogodg\Neoorm\Migrations\Operation\CreateIndex;
use Diogodg\Neoorm\Migrations\Operation\CreateTable;
use Diogodg\Neoorm\Migrations\Operation\DropCheckConstraint;
use Diogodg\Neoorm\Migrations\Operation\DropColumn;
use Diogodg\Neoorm\Migrations\Operation\DropForeignKey;
use Diogodg\Neoorm\Migrations\Operation\DropIndex;
use Diogodg\Neoorm\Migrations\Operation\DropPrimaryKey;
use Diogodg\Neoorm\Migrations\Operation\DropTable;
use Diogodg\Neoorm\Migrations\Operation\DropUniqueConstraint;
use Diogodg\Neoorm\Migrations\Operation\RenameColumn;
use Diogodg\Neoorm\Migrations\Operation\RenameTable;
use Diogodg\Neoorm\Migrations\Operation\SetTableComment;
use Diogodg\Neoorm\Migrations\Operation\SetTableOptions;
use Diogodg\Neoorm\Schema\ColumnDefinition;
use Diogodg\Neoorm\Schema\PrimaryKeyDefinition;
use Diogodg\Neoorm\Schema\SchemaDefinition;
use Diogodg\Neoorm\Schema\TableDefinition;
use Diogodg\Neoorm\Schema\TableOptions;
use Diogodg\Neoorm\Schema\Type\TypeName;
use Diogodg\Neoorm\Schema\Type\TypeSpec;

/**
 * Gerador de DDL do PostgreSQL 17.
 *
 * Duas divergências que valem ser ditas em voz alta:
 *
 * Comentário não é atributo de coluna aqui, é um comando à parte. Por isso
 * `compileCreateTable()` devolve o CREATE mais um `COMMENT ON` por comentário, em
 * vez de um statement só. Era exatamente isso que o sistema antigo não fazia:
 * o SQL vinha montado com o `COMMENT '...'` inline do MySQL e o driver pgsql
 * descartava a parte que não reconhecia, junto com o tamanho da coluna — todo
 * `VARCHAR(120)` virava `varchar` sem limite.
 *
 * Identity é `GENERATED BY DEFAULT`, nunca `ALWAYS`. Com `ALWAYS` o banco recusa
 * INSERT que informe o id explicitamente, o que quebraria import de dados, seed
 * com id fixo e qualquer teste que fixe chaves. O custo assumido é que a
 * distinção entre as duas formas não é representável no IR, e a introspecção
 * colapsa as duas em `autoIncrement`.
 *
 * Nada aqui qualifica nome por schema: quem decide onde os objetos moram é o
 * `search_path` da sessão, definido pelo runner a partir de `DBSCHEMA`.
 */
final class PgsqlDialect extends AbstractDialect
{
    /**
     * @param string|null $schema o `DBSCHEMA`, ou null para não mexer no `search_path`
     */
    public function __construct(private readonly ?string $schema = null)
    {
    }

    /**
     * Fixa o `search_path` da sessão no schema configurado.
     *
     * Nenhum DDL gerado aqui qualifica nome por schema, e é uma escolha: qualificar
     * gravaria o nome do schema dentro de todo arquivo `.sql` commitado, e aí mudar de
     * `public` para outro schema — ou aplicar a mesma migração em dois schemas, que é
     * como se faz multi-tenant no Postgres — exigiria reescrever o histórico inteiro.
     *
     * O preço de não qualificar é que o `search_path` passa a ser parte do contrato, e é
     * por isso que ele é fixado aqui em vez de ser herdado da configuração do usuário do
     * banco. Herdado, a mesma migração criaria tabela em lugares diferentes conforme quem
     * a rodou.
     *
     * @return list<string>
     */
    public function sessionSetup(): array
    {
        if ($this->schema === null || trim($this->schema) === '') {
            return [];
        }

        return ['SET search_path TO ' . $this->quoteIdentifier($this->schema)];
    }

    public function name(): string
    {
        return 'pgsql';
    }

    public function maxIdentifierLength(): int
    {
        return 63;
    }

    /**
     * DDL participa de transação. É o que permite ao runner aplicar uma migração
     * inteira e o próprio bookkeeping num único COMMIT: ou tudo entra, ou nada.
     */
    public function supportsTransactionalDdl(): bool
    {
        return true;
    }

    /**
     * Descarta `engine` e `collation` de tabela: conceitos que não existem aqui.
     *
     * Sem isso, um model que declara `engine: 'InnoDB'` faria todo `generate` contra o
     * PostgreSQL emitir uma operação de opções de tabela que compila para zero statements.
     * O arquivo `.sql` sairia vazio, a migração contaria como aplicada, e a comparação
     * seguinte pediria a mesma coisa de novo — para sempre.
     */
    public function normalizeForStorage(SchemaDefinition $schema): SchemaDefinition
    {
        $tables = [];

        foreach ($schema->tables as $table) {
            $tables[] = $table->options->isEmpty() ? $table : new TableDefinition(
                name: $table->name,
                columns: array_values($table->getColumns()),
                primaryKey: $table->primaryKey,
                uniqueConstraints: array_values($table->uniqueConstraints),
                indexes: array_values($table->indexes),
                foreignKeys: array_values($table->foreignKeys),
                checks: array_values($table->checks),
                comment: $table->comment,
                options: new TableOptions(),
            );
        }

        return new SchemaDefinition($tables);
    }

    protected function wrapIdentifier(string $identifier): string
    {
        return '"' . str_replace('"', '""', $identifier) . '"';
    }

    protected function wrapString(string $value): string
    {
        // No PostgreSQL a barra invertida não é especial dentro de uma string
        // comum (standard_conforming_strings, padrão desde a 9.1), então dobrar a
        // aspa simples é todo o escape necessário.
        return "'" . str_replace("'", "''", $value) . "'";
    }

    protected function renderBoolean(bool $value): string
    {
        return $value ? 'true' : 'false';
    }

    // ----------------------------------------------------------------- tipos

    public function renderType(TypeSpec $type): string
    {
        if ($this->checkType($type) !== null) {
            $this->rejectType($type);
        }

        $name = $type->name;

        // Grafias do PostgreSQL para tipos que o IR nomeia à moda do MySQL. São
        // as mesmas que o catálogo devolve, então a introspecção fecha o círculo
        // por TypeName::fromAlias().
        $rendered = match ($name) {
            TypeName::Int => 'INTEGER',
            TypeName::Double => 'DOUBLE PRECISION',
            TypeName::Float => 'REAL',
            TypeName::Decimal => 'NUMERIC',
            TypeName::TimestampTz => 'TIMESTAMPTZ',
            default => $name->value,
        };

        if ($type->precision !== null && $name->acceptsPrecision()) {
            // REAL e DOUBLE PRECISION não aceitam precisão no PostgreSQL; só
            // NUMERIC tem (precisão, escala) de verdade.
            if ($name === TypeName::Decimal) {
                return $rendered . '(' . $type->precision . ',' . ($type->scale ?? 0) . ')';
            }

            return $rendered;
        }

        if ($type->length !== null && $name->acceptsLength()) {
            return $rendered . '(' . $type->length . ')';
        }

        return $rendered;
    }

    // --------------------------------------------------------------- colunas

    protected function renderColumn(ColumnDefinition $column): string
    {
        if ($column->collation !== null) {
            throw new MigrationException(
                "Coluna '{$column->name}': collation por coluna não é suportada no PostgreSQL por esta "
                . 'biblioteca. Nomes de collation aqui dependem do locale do sistema operacional '
                . "('pt_BR.utf8', 'de-DE-x-icu') e nunca fechariam o round-trip entre máquinas. "
                . 'SchemaValidator recusa antes de chegar aqui.',
            );
        }

        $parts = [$this->quoteIdentifier($column->name), $this->renderType($column->type)];

        if ($column->autoIncrement) {
            if (!$column->default->isNone()) {
                throw new MigrationException(
                    "Coluna '{$column->name}': uma coluna identity não pode ter DEFAULT no PostgreSQL. "
                    . 'Escolha entre auto incremento e valor padrão.',
                );
            }

            $parts[] = 'GENERATED BY DEFAULT AS IDENTITY';
        }

        if ($column->notNull) {
            $parts[] = 'NOT NULL';
        }

        if (!$column->autoIncrement) {
            $default = $this->renderDefault($column->default);

            if ($default !== null) {
                $parts[] = $default;
            }
        }

        return implode(' ', $parts);
    }

    /**
     * Com `CONSTRAINT nome` explícito, sempre.
     *
     * O PostgreSQL guarda o nome, e omiti-lo faria o banco inventar
     * `{tabela}_pkey`, que não é o nome que o `ConstraintNamer` registra no
     * snapshot. Nomear é o que mantém as duas pontas concordando — e o differ
     * ainda compara PK só pela lista de colunas, para que um banco adotado com o
     * nome default do servidor não gere migração.
     */
    protected function inlinePrimaryKey(PrimaryKeyDefinition $primaryKey): string
    {
        return 'CONSTRAINT ' . $this->quoteIdentifier($primaryKey->name) . ' '
            . $this->primaryKeyBody($primaryKey);
    }

    // ------------------------------------------------------------- operações

    protected function compileCreateTable(CreateTable $operation): array
    {
        $table = $operation->table;

        $sql = 'CREATE TABLE ';

        if ($operation->ifNotExists) {
            $sql .= 'IF NOT EXISTS ';
        }

        $sql .= $this->quoteIdentifier($table->name) . ' ' . $this->tableBody($table);

        $statements = [$sql];

        if ($table->comment !== null) {
            $statements[] = $this->commentOnTable($table->name, $table->comment);
        }

        // Ordem de declaração das colunas: determinística, e a mesma que o
        // snapshot registra em columnOrder.
        foreach ($table->columns as $column) {
            if ($column->comment !== null) {
                $statements[] = $this->commentOnColumn($table->name, $column->name, $column->comment);
            }
        }

        return $statements;
    }

    protected function compileDropTable(DropTable $operation): array
    {
        return ['DROP TABLE ' . $this->quoteIdentifier($operation->table)];
    }

    protected function compileRenameTable(RenameTable $operation): array
    {
        return [$this->alterTable($operation->from) . ' RENAME TO ' . $this->quoteIdentifier($operation->to)];
    }

    protected function compileSetTableComment(SetTableComment $operation): array
    {
        return [$this->commentOnTable($operation->table, $operation->comment)];
    }

    /**
     * Engine e collation de tabela não existem no PostgreSQL.
     *
     * Lista vazia é a resposta correta, não um buraco: o IR é neutro e carrega os
     * dois campos porque o MySQL os tem, e `null` neles já significa "default do
     * servidor, não compare".
     */
    protected function compileSetTableOptions(SetTableOptions $operation): array
    {
        return [];
    }

    protected function compileAddColumn(AddColumn $operation): array
    {
        $statements = [
            $this->alterTable($operation->table) . ' ADD COLUMN ' . $this->renderColumn($operation->column),
        ];

        if ($operation->column->comment !== null) {
            $statements[] = $this->commentOnColumn(
                $operation->table,
                $operation->column->name,
                $operation->column->comment,
            );
        }

        return $statements;
    }

    protected function compileDropColumn(DropColumn $operation): array
    {
        return [
            $this->alterTable($operation->table)
            . ' DROP COLUMN ' . $this->quoteIdentifier($operation->column),
        ];
    }

    protected function compileRenameColumn(RenameColumn $operation): array
    {
        return [
            $this->alterTable($operation->table)
            . ' RENAME COLUMN ' . $this->quoteIdentifier($operation->from)
            . ' TO ' . $this->quoteIdentifier($operation->to),
        ];
    }

    /**
     * Um statement por aspecto alterado — o PostgreSQL não aceita outra coisa.
     *
     * A ordem não é arbitrária. O default sai antes da troca de tipo porque um
     * default que não converte para o tipo novo bloqueia a conversão inteira com
     * "default for column cannot be cast automatically", e volta depois: é o que
     * faz VARCHAR para INTEGER caber numa migração só em vez de exigir intervenção
     * manual.
     */
    protected function compileAlterColumn(AlterColumn $operation): array
    {
        $changes = $operation->changes;

        if ($changes->isEmpty()) {
            return [];
        }

        $prefix = $this->alterTable($operation->table)
            . ' ALTER COLUMN ' . $this->quoteIdentifier($operation->to->name);

        $statements = [];

        $dropsDefaultFirst = $changes->type && !$operation->from->default->isNone();

        if ($dropsDefaultFirst) {
            $statements[] = $prefix . ' DROP DEFAULT';
        }

        if ($changes->type) {
            $type = $this->renderType($operation->to->type);
            $column = $this->quoteIdentifier($operation->to->name);

            // USING explícito sempre: sem ele o PostgreSQL só aceita conversões
            // que considera implícitas, e qual conversão é implícita varia por par
            // de tipos. Um caminho único é um caminho testável.
            $statements[] = "{$prefix} TYPE {$type} USING {$column}::{$type}";
        }

        if ($changes->notNull) {
            $statements[] = $prefix . ($operation->to->notNull ? ' SET NOT NULL' : ' DROP NOT NULL');
        }

        $targetDefault = $this->renderDefault($operation->to->default);

        if ($targetDefault !== null && ($changes->default || $dropsDefaultFirst)) {
            $statements[] = "{$prefix} SET {$targetDefault}";
        } elseif ($targetDefault === null && $changes->default && !$dropsDefaultFirst) {
            $statements[] = $prefix . ' DROP DEFAULT';
        }

        if ($changes->autoIncrement) {
            $statements[] = $operation->to->autoIncrement
                ? $prefix . ' ADD GENERATED BY DEFAULT AS IDENTITY'
                : $prefix . ' DROP IDENTITY';
        }

        if ($changes->comment) {
            $statements[] = $this->commentOnColumn(
                $operation->table,
                $operation->to->name,
                $operation->to->comment,
            );
        }

        return $statements;
    }

    protected function compileAddPrimaryKey(AddPrimaryKey $operation): array
    {
        return [
            $this->addConstraint(
                $operation->table,
                $operation->primaryKey->name,
                $this->primaryKeyBody($operation->primaryKey),
            ),
        ];
    }

    protected function compileDropPrimaryKey(DropPrimaryKey $operation): array
    {
        // Diferente do MySQL, não há nada a fazer com a coluna identity antes: no
        // PostgreSQL identity e chave primária são independentes.
        return [$this->dropConstraint($operation->table, $operation->name)];
    }

    protected function compileAddUniqueConstraint(AddUniqueConstraint $operation): array
    {
        return [
            $this->addConstraint(
                $operation->table,
                $operation->constraint->name,
                'UNIQUE (' . $this->columnList($operation->constraint->columns) . ')',
            ),
        ];
    }

    protected function compileDropUniqueConstraint(DropUniqueConstraint $operation): array
    {
        return [$this->dropConstraint($operation->table, $operation->name)];
    }

    protected function compileCreateIndex(CreateIndex $operation): array
    {
        $index = $operation->index;

        $sql = 'CREATE ' . ($index->unique ? 'UNIQUE INDEX ' : 'INDEX ')
            . $this->quoteIdentifier($index->name)
            . ' ON ' . $this->quoteIdentifier($operation->table);

        // No PostgreSQL o USING vem depois da tabela; no MySQL, depois do nome do
        // índice. Mesma cláusula, posições diferentes.
        if ($index->method !== null) {
            $sql .= ' USING ' . $this->safeOptionValue($index->method, 'Método de índice');
        }

        $sql .= ' (' . $this->columnList($index->columns) . ')';

        return [$sql];
    }

    protected function compileDropIndex(DropIndex $operation): array
    {
        // Índice é objeto de schema, não de tabela: DROP INDEX não menciona a
        // tabela. A operação carrega o nome dela de todo jeito porque o MySQL
        // precisa.
        return ['DROP INDEX ' . $this->quoteIdentifier($operation->name)];
    }

    protected function compileAddForeignKey(AddForeignKey $operation): array
    {
        return [
            $this->addConstraint(
                $operation->table,
                $operation->foreignKey->name,
                $this->foreignKeyBody($operation->foreignKey),
            ),
        ];
    }

    protected function compileDropForeignKey(DropForeignKey $operation): array
    {
        return [$this->dropConstraint($operation->table, $operation->name)];
    }

    protected function compileAddCheckConstraint(AddCheckConstraint $operation): array
    {
        return [
            $this->addConstraint(
                $operation->table,
                $operation->check->name,
                'CHECK (' . $operation->check->expression . ')',
            ),
        ];
    }

    protected function compileDropCheckConstraint(DropCheckConstraint $operation): array
    {
        return [$this->dropConstraint($operation->table, $operation->name)];
    }

    // ------------------------------------------------------------ auxiliares

    private function commentOnTable(string $table, ?string $comment): string
    {
        return 'COMMENT ON TABLE ' . $this->quoteIdentifier($table)
            . ' IS ' . $this->quoteLiteral($comment);
    }

    private function commentOnColumn(string $table, string $column, ?string $comment): string
    {
        return 'COMMENT ON COLUMN ' . $this->quoteIdentifier($table) . '.' . $this->quoteIdentifier($column)
            . ' IS ' . $this->quoteLiteral($comment);
    }

    // ------------------------------------------------------------------- DML

    /**
     * As duas cláusulas são independentes aqui: OFFSET sozinho é válido, ao
     * contrário do MySQL, que precisa de um limite sentinela.
     */
    public function limitOffsetClause(?string $limitPlaceholder, ?string $offsetPlaceholder): string
    {
        $parts = [];

        if ($limitPlaceholder !== null) {
            $parts[] = 'LIMIT ' . $limitPlaceholder;
        }

        if ($offsetPlaceholder !== null) {
            $parts[] = 'OFFSET ' . $offsetPlaceholder;
        }

        return implode(' ', $parts);
    }

    public function supportsReturning(): bool
    {
        return true;
    }

    public function supportsReturningOnModify(): bool
    {
        return true;
    }

    public function caseInsensitiveLike(string $left, string $right): string
    {
        return $left . ' ILIKE ' . $right;
    }

    public function supportsNullsPlacement(): bool
    {
        return true;
    }

    public function connectionSetup(): array
    {
        return [...$this->sessionSetup(), "SET TIME ZONE 'UTC'"];
    }
}
