<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen\Inserts;

/**
 * Payload de INSERT para `schedule_user`.
 *
 * Coluna com DEFAULT ou auto incremento é opcional: deixá-la em `null` OMITE a
 * coluna do INSERT, e o banco aplica o próprio padrão.
 */
final readonly class ScheduleUserInsert
{
    public function __construct(
        public int $schedule_id,
        public int $user_id,
    ) {
    }

    /**
     * @return array<string,mixed>
     */
    public function toColumns(): array
    {
        $columns = [];

        $columns['schedule_id'] = $this->schedule_id;

        $columns['user_id'] = $this->user_id;

        return $columns;
    }
}
