<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen\Inserts;

use DateTimeImmutable;
use Diogodg\Neoorm\Runtime\Unspecified;
use Tests\Golden\Codegen\Enums\UsersStatus;

/**
 * Payload de INSERT para `users`.
 *
 * Coluna com DEFAULT ou auto incremento é opcional: deixá-la em `null` OMITE a
 * coluna do INSERT, e o banco aplica o próprio padrão.
 */
final readonly class UsersInsert
{
    /**
     * @param string $name Nome do usuário
     * @param numeric-string|null $balance null = usa o DEFAULT da coluna
     * @param bool|null $active null = usa o DEFAULT da coluna
     * @param DateTimeImmutable|null $created_at null = usa o DEFAULT da coluna
     * @param UsersStatus|null $status null = usa o DEFAULT da coluna
     * @param string|Unspecified|null $nickname Unspecified = usa o DEFAULT; null = grava NULL
     * @param int|null $id null = o banco gera
     */
    public function __construct(
        public string $name,
        public ?string $phone = null,
        public ?string $balance = null,
        public ?bool $active = null,
        public ?DateTimeImmutable $created_at = null,
        public ?UsersStatus $status = null,
        public string|Unspecified|null $nickname = Unspecified::Value,
        public mixed $metadata = null,
        public ?string $avatar = null,
        public ?string $code = null,
        public ?int $id = null,
    ) {
    }

    /**
     * @return array<string,mixed>
     */
    public function toColumns(): array
    {
        $columns = [];

        $columns['name'] = $this->name;

        if ($this->phone !== null) {
            $columns['phone'] = $this->phone;
        }

        if ($this->balance !== null) {
            $columns['balance'] = $this->balance;
        }

        if ($this->active !== null) {
            $columns['active'] = $this->active;
        }

        if ($this->created_at !== null) {
            $columns['created_at'] = $this->created_at;
        }

        if ($this->status !== null) {
            $columns['status'] = $this->status;
        }

        if (!$this->nickname instanceof Unspecified) {
            $columns['nickname'] = $this->nickname;
        }

        if ($this->metadata !== null) {
            $columns['metadata'] = $this->metadata;
        }

        if ($this->avatar !== null) {
            $columns['avatar'] = $this->avatar;
        }

        if ($this->code !== null) {
            $columns['code'] = $this->code;
        }

        if ($this->id !== null) {
            $columns['id'] = $this->id;
        }

        return $columns;
    }
}
