<?php
    define("DRIVER","mysql");
    define("DBHOST","localhost");
    define("DBPORT","3306");
    define("DBNAME","bd");
    define("DBCHARSET","utf8mb4");
    define("DBUSER","root");
    define("DBPASSWORD","");
?>