<?php

declare(strict_types=1);

// @generated by neoorm — não edite à mão.
// Regenere com: vendor/bin/neoorm generate:types

namespace Tests\Golden\Codegen\Enums;

/**
 * Valores de `users`.`status`.
 */
enum UsersStatus: string
{
    case Ativo = 'ativo';
    case Bloqueado = 'bloqueado';
    case Pendente = 'pendente';
}
